### PR TITLE
Don't publish unused assets in package

### PR DESCRIPTION
**Pull request by asilvas**
Thanks for the module!

### CODE REVIEW

**Comment by kesla** [comment]
I guess the real problem here is that the tests files are relatively big?

The readme should be published to show up on https://www.npmjs.com/package/smart-crop

**Comment by asilvas** [comment]
Not a big deal, but yeah just good practice to not publish unused files. Fixed readme.

**Comment by kesla** [comment]
@asilvas I went with a jump here - this was released as v1.0.0! :boom:

**Comment by asilvas** [comment]
+1

**Pull request merged**
